LLM_PROVIDER="openai"
MODEL_ID="gpt-4o-mini"

TEMPERATURE = 0.2
MAX_ITERATIONS = 30
# Agent Settings
AGENT_TYPE = "LLMCompilerAgent"

CODE_EXECUTION_TIMEOUT: 100

LLM_VISION_PROVIDER="openai"
MODEL_VISION_ID="gpt-4o-mini"